version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"  # Web UIのポート
            - "1025:1025"  # SMTPポート

    nodejs:
        image: node:14  # Node.jsの公式イメージ（バージョン14を使用）
        volumes:
            - ./src:/usr/src/app  # ローカルのsrcディレクトリをコンテナ内の/usr/src/appにマウント
        working_dir: /usr/src/app  # コンテナ内での作業ディレクトリ
        command: npm start  # コンテナ起動時に実行するコマンド（例: npm start）
        ports:
            - "3000:3000"  # Node.jsアプリケーションのポートを公開
        depends_on:
            - mysql
            - php